name: npm_install_from_cache
description: Install npm modules from cache and if there is no cache then install them from scratch
runs:
  using: composite
  steps:
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache/restore@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-build-master-cache-${{ hashFiles('./package-lock.json') }}

    - name: Install npm modules
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
