name: publish_to_cf_pages_staging
description: publish to cloudflare pages (staging)
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: "Cloudflare account id"
    required: true
  CLOUDFLARE_API_TOKEN:
    description: "Cloudflare token"
    required: true
runs:
  using: composite
  steps:
    - name: Publish to cloudflare pages (staging)
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
      run: |-
        cd www
        npx wrangler pages publish . --project-name=deriv-binary-bot-pages --branch=staging
        echo "New staging website - http://staging.cf-pages-deriv-binary-bot.deriv.com"
      shell: bash
