name: Versioning Action
description: version the release and store it in the environment variable
inputs:
  RELEASE_TYPE:
    description: 'release type'
    required: true
runs:
  using: composite
  steps:
    - name: Set version
      env:
        RELEASE_TYPE: ${{ inputs.RELEASE_TYPE }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}
      run: |
        current_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        version="$RELEASE_TYPE-GH_Run#:$GITHUB_RUN_NUMBER-Date:$current_date"
        echo "Setting version to: $version"
        echo "VERSION=$version" >> $GITHUB_ENV
      shell: bash
