
name: Versioning Action
description: version the release and store it in the environment variable
inputs:
  RELEASE_TYPE:
    description: 'release type'
    required: true
runs:
  using: composite
  steps:
    - name: Set version
      run: |
        current_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        version="${{ inputs.RELEASE_TYPE }}-GH_Run#:${{ github.run_number }}-Date:$current_date"
        echo "Setting version to: $version"
        echo "VERSION=$version" >> $GITHUB_ENV
      shell: bash
