name: send_slack_notifications
description: Send Slack notifications
inputs:
  SLACK_WEBHOOK_URL:
    description: "Slack webhook URL"
    required: true
  status:
    description: "Job status"
    required: true
  release_type:
    description: "Release type"
    required: true
  version:
    description: "Version"
    required: true
    default: "N/A"
  app_url:
    description: "App URL"
    required: true
    default: "https://bot.deriv.com/"
runs:
  using: composite
  steps:
    - name: Send Slack Notification on Success
      if: inputs.status == 'success'
      uses: 'deriv-com/shared-actions/.github/actions/send_slack_notification@master'
      with:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        MESSAGE: ${{ inputs.RELEASE_TYPE }} Release succeeded for ${{ inputs.APP_URL }} with version ${{ inputs.VERSION }}

    - name: Send Slack Notification on Failure
      if: inputs.status == 'failure'
      uses: 'deriv-com/shared-actions/.github/actions/send_slack_notification@master'
      with:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        MESSAGE: ${{ inputs.RELEASE_TYPE }} Release failed for ${{ inputs.APP_URL }} with version ${{ inputs.VERSION }}
