#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "\e[1;41m[husky]: performing pre-commit checks"
npm test
echo -e "\e[1;42m[husky]: all the tests were passed"
npx lint-staged
echo -e "\e[1;42m[husky]: pre-commit check successful"